# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: bulbistry

before:
  hooks:
    - go mod tidy
    - grep -qF '"{{ .Tag }}"' internal/version/version.go 

builds:
  - main: ./cmd/bulbistry/main.go
    goos: 
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3
    

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}_checksums.txt"
  algorithm: sha256

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Tag }}"
  prefix_template: "{{ .ProjectName }}-{{ .Tag }}/"
  format: "tar.gz"

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.sbom"

dockers_v2:
  - images:
      - "ghcr.io/csjewell/bulbistry"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Bulbistry minimal registry"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
#      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.source": "https://github.com/csjewell/bulbistry"
      "org.opencontainers.image.url": "https://github.com/csjewell/bulbistry"
      "org.opencontainers.image.documentation": "https://github.com/csjewell/bulbistry"
      "org.opencontainers.image.authors": "Curtis Jewell <bulbistry@curtisjewell.name> and other contributors"
      "org.opencontainers.image.title": "Bulbistry"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.base.name": "cgr.dev/chainguard/static:latest"



#    dockerfile: "docker/Dockerfile"

#    use: buildx 

#    extra_files:
#      - docker/blob

#    skip_push: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

#announce:
#  skip: "{{gt .Patch 0}}"
